import { MarketRegime, RegimeConfidence } from "../lib/regimeConfig";

export type Signal = "BUY" | "SELL" | "HOLD";

export type PositionStatus = "OPEN" | "CLOSED";
export type ExitReason = "STOP_LOSS" | "TAKE_PROFIT" | "TRAILING_STOP" | "MANUAL" | "SIGNAL_EXIT";
export type EntryReason = "BREAKOUT_BUY_SIGNAL" | "MANUAL_OPEN";
export type JournalReason = EntryReason | ExitReason;

export type Candle = {
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
};

export type Position = {
  instrument: string;
  entryPrice: number;
  quantity: number;
  positionSizeUsd?: number;
  sizingMode?: "fixed" | "dynamic";
  sizingRegimeMultiplier?: number;
  sizingScoreMultiplier?: number;
  openedAt: string;
  stopLoss: number;
  takeProfit: number;
  highestSeenPrice: number;
  entryRegime?: MarketRegime;
  entryRegimeConfidence?: RegimeConfidence;
  entryBreadthScore?: number;
  entryVolatilityPct?: number;
  entryEmaSpreadPct?: number;
  mfeUsd?: number;
  maeUsd?: number;
  exitReason?: ExitReason;
  status: PositionStatus;
};

export type JournalEntry = {
  instrument: string;
  side: "BUY" | "SELL";
  entryPrice: number;
  exitPrice?: number;
  quantity: number;
  positionSizeUsd?: number;
  sizingMode?: "fixed" | "dynamic";
  sizingRegimeMultiplier?: number;
  sizingScoreMultiplier?: number;
  openedAt: string;
  closedAt?: string;
  pnl?: number;
  reason: JournalReason;
  exitReason?: ExitReason;
  entryRegime?: MarketRegime;
  entryRegimeConfidence?: RegimeConfidence;
  entryBreadthScore?: number;
  entryVolatilityPct?: number;
  entryEmaSpreadPct?: number;
};

export type BotConfig = {
  executionMode: "paper" | "live";
  liveTradingEnabled: boolean;
  liveExecutionDryRun: boolean;
  cryptocomApiKey?: string;
  cryptocomApiSecret?: string;
  cryptocomExchangePrivateBaseUrl: string;
  instruments: string[];
  timeframe: string;
  lookback: number;
  breakoutVolumeMultiplier: number;
  stopLossPct: number;
  takeProfitPct: number;
  paperStartingCapitalUsd: number;
  paperTradeSizeUsd: number;
  paperSizeMinUsd: number;
  paperSizeMaxUsd: number;
  paperSizeUseDynamic: boolean;
  maxOpenPositions: number;
  pollIntervalMs: number;
  enableTrailingStop: boolean;
  trailingStopPct: number;
  enableSignalExit: boolean;
  breakoutBufferPct: number;
  minRangePct: number;
  useRelaxedEntry: boolean;
  atrPeriod: number;
  minAtrPct: number;
  minVolatilityRangePct: number;
  volFilterEnabled: boolean;
  scannerEnabled: boolean;
  scannerMaxInstruments: number;
  scannerQuoteFilter: string;
  scannerTopN: number;
  scannerMin24hVolume: number;
  scannerUseCandleConfirmation: boolean;
  alertsEnabled: boolean;
  alertMode: "console" | "webhook" | "telegram";
  alertWebhookUrl?: string;
  telegramBotToken?: string;
  telegramChatId?: string;
  dataCbMaxConsecutiveMockCycles: number;
  dataCbMaxConsecutiveFetchFailureCycles: number;
  dataCbMaxStaleCandleCycles: number;
  dataCbMaxConsecutivePriceRejectCycles: number;
  dataCbHealthyCyclesToClear: number;
  orphanPositionMaxUnpricedCycles: number;
  marketDataFreshnessMs: number;
  marketDataHighDisagreementBps: number;
  marketDataMediumDisagreementBps: number;
  orphanWarningCycles: number;
  orphanStaleCycles: number;
  orphanCycles: number;
  orphanQuarantineCycles: number;
  allowLastGoodPriceMarking: boolean;
  allowLowConfidenceEntries: boolean;
  minRewardRiskBull: number;
  minRewardRiskNeutral: number;
  minTpDistancePct: number;
  maxSlDistancePct: number;
  minCandidateScoreNeutral: number;
};
